apiVersion: v1
kind: ConfigMap
metadata:
  name: tweets
  labels:
    strimzi.io/kind: topic
    strimzi.io/cluster: my-cluster
data:
  name: tweets
  partitions: "1"
  replicas: "3"
  config: |
          {
            "retention.bytes": "64000000",
            "segment.bytes": "16000000"
          }
