apiVersion: v1
kind: ConfigMap
metadata:
  name: twitter-feed
  labels:
    strimzi.io/kind: topic
    strimzi.io/cluster: my-cluster
data:
  name: twitter-feed
  partitions: "10"
  replicas: "3"
  config: |
          {
            "retention.bytes": "256000000",
            "segment.bytes": "32000000"
          }
